### ISSUE TITLE
Library file libsasl2.so.2 not found

### ISSUE THREAD

**Issue by sudipto84goswami** [toddlipcon/python-sasl#12]
Getting error as "ImportError: libsasl2.so.2: cannot open shared object file: No such file or directory"

Just trying to import the package using import sasl and this is throwing the above mentioned error:

>>> import sasl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "***/site-packages/sasl/__init__.py", line 15, in <module>
    from sasl.saslwrapper import *
ImportError: libsasl2.so.2: cannot open shared object file: No such file or directory
>>>

**Comment by ColdZoo** [comment]
will symbol linking libsasl2so.3 help?
