### ISSUE TITLE
OSX Usage

### ISSUE THREAD

**Issue by quasiben** [toddlipcon/python-sasl#5]
I've built sasl with the following command:

```
pip install sasl --global-option=build_ext --global-option="-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sasl/"
```

The above installs successfully but on import i receive the error below:
```
(clusto)quasiben@dirty-horse:~$ python -c 'import sasl;'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/quasiben/anaconda/envs/clusto/lib/python2.7/site-packages/sasl/__init__.py", line 1, in <module>
    from sasl.saslwrapper import *
  File "/Users/quasiben/anaconda/envs/clusto/lib/python2.7/site-packages/sasl/saslwrapper.py", line 7, in <module>
    import _saslwrapper
ImportError: dlopen(/Users/quasiben/anaconda/envs/clusto/lib/python2.7/site-packages/_saslwrapper.so, 2): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /Users/quasiben/anaconda/envs/clusto/lib/python2.7/site-packages/_saslwrapper.so
  Expected in: dynamic lookup
```

Thoughts?

**Comment by laserson** [comment]
Does `pip install sasl` not work?

**Comment by ilovejs** [comment]
g++ -bundle -undefined dynamic_lookup -L/Users/XXX/anaconda3/envs/sci_2.7/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/sasl/saslwrapper.o -L/Users/XXX/anaconda3/envs/sci_2.7/lib -lsasl2 -o build/lib.macosx-10.6-x86_64-2.7/sasl/saslwrapper.so
ld: library not found for -lgcc
